name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy Firebase
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Firebase
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > firebase-key.json

      - name: Deploy to Firebase Hosting
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-key.json
          firebase deploy --project acessos-bancarios --only hosting
