name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Autenticar com Conta de Serviço
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}'

      - name: Deploy Firebase Hosting
        run: firebase deploy --project acessos-bancarios --only hosting
